include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template.yml'

variables:
  HIS_ID: 40064
  ENABLE_H5: 'true'
  WORK_DIR: 'packages/40064'
  DIST_PATH: 'packages/40064/dist'
  ENABLE_PROD_PREVIEW: 'true'
