include:
  - local: 'packages/**/.gitlab-ci.yml'
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^\d{3,6}-.*/ || CI_COMMIT_TAG =~ /^release-^\d{3,6}-.*/
