include:
  - local: 'packages/40070/.gitlab-ci.yml'
  - local: 'packages/40009/.gitlab-ci.yml'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^\d{3,6}-.*/ || $CI_COMMIT_TAG =~ /^release-\d${3,6}-.*/
      when: never
    - when: always

# # 无用的ci，用来防止gitlab报错
ci:
  rules:
    - if: $CI_COMMIT_BRANCH !~ /^\d{3,6}-.*/ && $CI_COMMIT_TAG !~ /^release-\d${3,6}-.*/
  script:
    - exit 0
  tags:
    - kq-test
