include:
  - local: 'packages/40070/.gitlab-ci.yml'
  - local: 'packages/40009/.gitlab-ci.yml'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^\d{3,6}-.*/ || $CI_COMMIT_TAG =~ /^release-\d${3,6}-.*/
      when: never
    - when: always
