stages:
  - build
  - deploy
  - prod-42

include:
  - local: 'packages/40070/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40070-.*/ || $CI_COMMIT_TAG =~ /^release-40070-.*/
  - local: 'packages/40026/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40026-.*/ || $CI_COMMIT_TAG =~ /^release-40026-.*/
  - local: 'packages/40009/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40009.*/ || $CI_COMMIT_TAG =~ /^release-40009.*/
  - local: 'packages/40011/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40011.*/ || $CI_COMMIT_TAG =~ /^release-40011.*/
  - local: 'packages/2219/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^2219.*/ || $CI_COMMIT_TAG =~ /^release-2219.*/
  - local: 'packages/40074/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40074.*/ || $CI_COMMIT_TAG =~ /^release-40074.*/
  - local: 'packages/40019/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40019.*/ || $CI_COMMIT_TAG =~ /^release-40019.*/
  - local: 'packages/40064/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40064.*/ || $CI_COMMIT_TAG =~ /^release-40064.*/
  - local: 'packages/40013/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40013.*/ || $CI_COMMIT_TAG =~ /^release-40013.*/
  - local: 'packages/40012/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40012.*/ || $CI_COMMIT_TAG =~ /^release-40012.*/

# 无用的ci，用来防止gitlab报错
ci:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH !~ /^\d{3,6}-.*/ && $CI_COMMIT_TAG !~ /^release-\d{3,6}-.*/ && '$CI_PIPELINE_SOURCE != "merge_request_event"'
  script:
    - exit 0
  tags:
    - kq-front-test
