workflow:
  rules:
    # remove detached merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^40070-.*/ || $CI_COMMIT_TAG =~ /^release-40070-.*/
      when: always
      variables:
        HIS_ID: '40070'
        ENABLE_H5: 'true'
        WORK_DIR: 'packages/40070'
        DIST_PATH: 'packages/40070/dist'
    - when: never

include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template-no-workflow.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^40070-.*/ || $CI_COMMIT_TAG =~ /^release-40070-.*/
