include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template-no-workflow.yml'

variables:
  HIS_ID: '40070'
  ENABLE_H5: 'true'
  WORK_DIR: 'packages/40070'
  DIST_PATH: 'packages/40070/dist'
