include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template.yml'

variables:
  HIS_ID: 40072
  ENABLE_H5: 'true'
   # 是否启用支付宝小程序
  ENABLE_ALI: 'true'
  WORK_DIR: 'packages/40072'
  DIST_PATH: 'packages/40072/dist'
