workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^40009-.*/ || $CI_COMMIT_TAG =~ /^release-40009-.*/
      variables:
        HIS_ID: 40009
        ENABLE_H5: 'true'
        WORK_DIR: 'packages/40009'
        DIST_PATH: 'packages/40009/dist'
    - when: never

include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template.yml'
