include:
  - project: 'fe-his-groups/apps/common'
    ref: main
    file: '.gitlab-ci-template.yml'

variables:
  HIS_ID: 40011
  ENABLE_H5: 'true'
  WORK_DIR: 'packages/40011'
  DIST_PATH: 'packages/40011/dist'
